In [1]:
x = [1, 2, 3, 4, 5]
x

# using numpy
import numpy as np
x = np.array([1, 2, 3, 4, 5])

print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
## matrices

m = np.array([[1, 5, 2],
              [4, 7, 4],
              [2, 0, 9]])

# view matrix
print(m)

# view dimensions
print(m.shape)

[[1 5 2]
 [4 7 4]
 [2 0 9]]
(3, 3)


In [3]:
# matrix transpose
print('Matrix Transpose:\n', m.transpose(), '\n')

Matrix Transpose:
 [[1 4 2]
 [5 7 0]
 [2 4 9]] 



In [4]:
# matrix determinant
print ('Matrix Determinant:', np.linalg.det(m), '\n')

Matrix Determinant: -105.00000000000006 



In [5]:
# matrix inverse
m_inv = np.linalg.inv(m)
print ('Matrix inverse:\n', m_inv, '\n')

Matrix inverse:
 [[-0.6         0.42857143 -0.05714286]
 [ 0.26666667 -0.04761905 -0.03809524]
 [ 0.13333333 -0.0952381   0.12380952]] 



In [6]:
# identity matrix (result of matrix x matrix_inverse)
iden_m =  np.dot(m, m_inv)
iden_m = np.round(np.abs(iden_m), 0)
print ('Product of matrix and its inverse:\n', iden_m)


Product of matrix and its inverse:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# descriptive statistics
import scipy as sp
import numpy as np
from scipy import stats
# get data
nums = np.random.randint(1,20, size=(1,15))[0]
print('Data: ', nums)

# get descriptive stats
print ('Mean:', sp.mean(nums))
print ('Median:', sp.median(nums))
print ('Mode:', sp.stats.mode(nums))
print ('Standard Deviation:', sp.std(nums))
print ('Variance:', sp.var(nums))
print ('Skew:', sp.stats.skew(nums))
print ('Kurtosis:', sp.stats.kurtosis(nums))

Data:  [13 18 14  7  6 18 12  4 19 16 12 17  8 10 16]
Mean: 12.666666666666666
Median: 13.0
Mode: ModeResult(mode=array([12]), count=array([2]))
Standard Deviation: 4.628414655389275
Variance: 21.422222222222217
Skew: -0.3597956675863459
Kurtosis: -1.1110216766240246
